name: java-maven-docker
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Increase patch version
      run: |
        cd myapp
        currentVersion=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        nextVersion=${currentVersion%.*}.$((${currentVersion##*.}+1))
        echo "nextVersion=$nextVersion" >> "$GITHUB_ENV"
        echo $nextVersion >> version.txt
        mvn versions:set -DnewVersion=$nextVersion

    - name: Build with Maven
      run: mvn -B clean package --file myapp/pom.xml

    - name: Create JAR artifact
      uses: actions/upload-artifact@v2
      with:
        name: myapp
        path: myapp/target/myapp-${{ env.nextVersion }}.jar
    
    - name: Create Version artifact
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: myapp/version.txt

  build_docker_image:
    needs: build_artifact
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    
    - name: Download JAR artifact 
      uses: actions/download-artifact@v2
      with:
        name: myapp
   
    - name: Download Version artifact 
      uses: actions/download-artifact@v2
      with:
        name: version

    - name: Set tag version
      run : |
         echo "newVersion=$(cat version.txt)" >> "$GITHUB_ENV"

    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        push: true
        tags: barohayon89/mayapp:${{ env.newVersion}}
        context: .
        build-args: ARTIFACT_PATH=myapp-${{ env.newVersion}}.jar
